### ISSUE TITLE
Support concrete pubkeys/hashes, descriptors and address generation

### ISSUE THREAD

**Issue by shesek** [shesek/minsc#2]

**Comment by philbertw4** [comment]
Hi @shesek, thanks very much for making min.sc -- it really seems to be a fantastic tool. From a usability standpoint, if I understand correctly, right now it is not trivial to take the output from min.sc (e.g. the generated bitcoin script) and turn it into a form that people can actually send btc to. Is that what this issue #2 pertains to?

In thinking about this, it looks like the minsc compiler already recompiles on every keystroke. I wonder if some sort of spreadsheet-like interface would be a good way to allow for going full cycle and putting in concrete values?

**Comment by shesek** [comment]
> ... Is that what this issue #2 pertains to?

That is correct. I'm looking to add support for providing actual pubkey values rather than just their nicknames, and getting the complete bitcoin script that incorporates them. I'd also like to add support for output descriptors and provide the address representation of the script based on that.

Both of these will become much easier to implement in Minsc once I switch over from sipa-miniscript to rust-miniscript, which is also planned (#1).

> I wonder if some sort of spreadsheet-like interface would be a good way to allow for going full cycle and putting in concrete values?

I considered that too, but I think that at least initially I will simply make it part of the program. Something like this:

```
$user_pk = pk(tpubD6..z7n/0/*);
$service_pk = pk(tpubE8..x1Q/0/*);

pk($user_pk) && (9@pk($service_pk) || older(90 days))
```

**Comment by philbertw4** [comment]
Thanks for the reply, and sorry for my delay. I think what you propose makes the most sense too initially. A couple more followup questions if you do not mind, do you then envision there existing a Minsc runtime which communicates with a bitcoin full node such that it could assist with signatures and ultimately broadcasting of the transaction(s)?  Or do you view that as out-of-scope of Minsc?

**Comment by shesek** [comment]
> do you then envision there existing a Minsc runtime which communicates with a bitcoin full node such that it could assist with signatures and ultimately broadcasting/monitoring of the transaction(s)? Or do you view that as out-of-scope of Minsc?

Out of scope for the Minsc engine itself, but definitely in scope for the overall experience I'd like to eventually provide on the min.sc playground. The other pieces of the puzzle are [bwt](https://github.com/shesek/bwt) to watch the chain for utxos, PSBT to communicate unsigned/partially signed transactions, and a miniscript-enabled wallet that could sign these transactions. The best candidate for the signing part appears to be [bdk](https://github.com/bitcoindevkit/bdk/), which I could also integrate into the web playground using wasm.

--

Chatting with you has gotten me to look into porting to rust-miniscript. I have a working version on master, with new data types and functions for descriptors, addresses, (x)pubkeys, hashes and compiled miniscripts, available for experimentation at https://min.sc/v0.2.

The UI isn't worked out at all, all the newly available data is just tucked in there. And none of the new features are documented on the website. But I wrote up a [quick example here](https://min.sc/v0.2/#c=%2F%2F%20Supports%20xpubs%20and%20standalone%20keys%0A%24alice%20%3D%20xpub68Gmy5EdvgibQVfPdqkBBCHxA5htiqg55crXYuXoQRKfDBFA1WEjWgP6LHhwBZeNK1VTsfTFUHCdrfp1bgwQ9xv5ski8PX9rL2dZXvgGDnw%2F9%2F0%3B%0A%24bob%20%3D%2003a5cc183f0676b681e8f8d2829c3d3a76d5c4e1c1c6e4d01cda5df82614e1c32d%3B%0A%0A%2F%2F%20Key%20derivation%20works%20at%20runtime%0A%24account%20%3D%2010%3B%0A%24policy%20%3D%20pk%28%24alice%2F%24account%2F0%2F*%29%20%26%26%20older%281%20month%29%3B%0A%0A%2F%2F%20Explicit%20Policy%20-%3E%20Miniscript%20-%3E%20Descriptor%20-%3E%20Address%0A%24miniscript%20%3D%20miniscript%28%24policy%29%3B%0A%24descriptor%20%3D%20wsh%28%24miniscript%29%3B%0A%24address%20%3D%20address%28%24descriptor%29%3B%0A%0A%2F%2F%20Descriptors%20can%20be%20derived%20similarly%20to%20keys%0A%24address2%20%3D%20address%28%24descriptor%2F10%29%3B%0A%0A%2F%2F%20Policies%2C%20Miniscripts%20and%20Keys%20get%20auto-coerced%20into%20descriptors%2C%20so%20this%20works%20too%3A%0A%24address3%20%3D%20address%28%24policy%2F10%29%3B%20%2F%2F%20%3D%3D%20address%28wsh%28miniscript%28%24policy%29%29%2F10%29%0A%24address4%20%3D%20address%28%24alice%2F12%29%3B%20%2F%2F%20%3D%3D%20address%28wpkh%28%24alice%2F12%29%29%0A%0A%5B%20%24policy%2C%20%24address%2C%20%24address2%2C%20%24address3%2C%20%24address4%20%5D) that demonstrates the new stuff. Feedback is appreciated :)

**Comment by philbertw4** [comment]
Thanks for your reply, and also for pointing out those other tools (bwt and bdk). 

>The other pieces of the puzzle ...

Yes, that is exactly the challenge. I think that the more of this puzzle that the min.sc playground can provide (at least on, say, signet), the better. Even people who are relatively versed in bitcoin I think can get quite bogged down by the complexity of wrangling so many pieces together just to test an idea, and seeing something like minsc (the language) and min.sc (the playground, as it evolves) is a breath of fresh air!

> ... porting to rust-miniscript. I have a working version on master, with new data types and functions for descriptors, addresses, (x)pubkeys, hashes and compiled miniscripts, available for experimentation at https://min.sc/v0.2.

This is a great improvement! Thank you! 

I am not sure if the following feedback is helpful at this stage or not (and/or if it should be in a separate issue), but here it goes:
1. If/when the min.sc playground is hooked up to a (signet/mainnet) full node, then I think it might be possible to provide a sort of auto-completion for UTXOs? 
2. The thought here is that, by starting from a blank-slate playground, one could type the first few characters of a specific UTXO's hash (basically, whatever minimum number of characters is necessary uniquely define the UTXO), or choose an example, even randomly from the current UTXO set, and then the user interactively "explore" how to spend it.

**Comment by shesek** [comment]
>  I think that the more of this puzzle that the min.sc playground can provide (at least on, say, signet), the better.

Yes, definitely! Might take a little while, but I'm aiming to get there. :)

> specific UTXO's hash ...  then the user interactively "explore" how to spend it.

The utxo isn't enough for spending, you'll have to also know the policy (or miniscript/descriptor) associated with the output.

So spending has to involve the user providing the policy at some point. And if we have that, the playground could generate the addresses and automatically look up their unspent outputs (via bwt), so the user could pick them from a list instead of typing them.

**Comment by shesek** [comment]
Implemented!

**Comment by philbertw4** [comment]
Sorry for the delay. I will play more with these new features this week. Nice work!
