### ISSUE TITLE
How to express threshold of thresholds?

### ISSUE THREAD

**Issue by ChristopherA** [shesek/minsc#6]
How do I create a threshold of thresholds? For instance, this special 4 of 9:

```
$family = 2 of [ pk(A), pk(B), pk(C) ]; 
$colleagues = 2 of [ pk(D), pk(E), pk(F) ];
$friends = 2 of [ pk(G), pk(H), pk(I) ];
$recovery = 2 of [ $family, $colleagues, $friends ];

**Comment by shesek** [comment]
Hi! Sorry for the slow reply, I somehow missed this.

What you wrote is correct, the only thing missing is that the program needs to end with an expression that represents the main policy.

It'll work if you return the `$recovery` at the end: ([try](https://min.sc/#c=%24family%20%3D%202%20of%20%5B%20pk%28A%29%2C%20pk%28B%29%2C%20pk%28C%29%20%5D%3B%20%0A%24colleagues%20%3D%202%20of%20%5B%20pk%28D%29%2C%20pk%28E%29%2C%20pk%28F%29%20%5D%3B%0A%24friends%20%3D%202%20of%20%5B%20pk%28G%29%2C%20pk%28H%29%2C%20pk%28I%29%20%5D%3B%0A%24recovery%20%3D%202%20of%20%5B%20%24family%2C%20%24colleagues%2C%20%24friends%20%5D%3B%0A%0A%24recovery))

```hack
$family = 2 of [ pk(A), pk(B), pk(C) ]; 
$colleagues = 2 of [ pk(D), pk(E), pk(F) ];
$friends = 2 of [ pk(G), pk(H), pk(I) ];
$recovery = 2 of [ $family, $colleagues, $friends ];

$recovery
```

Or like this: ([try](https://min.sc/#c=%24family%20%3D%202%20of%20%5B%20pk%28A%29%2C%20pk%28B%29%2C%20pk%28C%29%20%5D%3B%20%0A%24colleagues%20%3D%202%20of%20%5B%20pk%28D%29%2C%20pk%28E%29%2C%20pk%28F%29%20%5D%3B%0A%24friends%20%3D%202%20of%20%5B%20pk%28G%29%2C%20pk%28H%29%2C%20pk%28I%29%20%5D%3B%0A%0A2%20of%20%5B%20%24family%2C%20%24colleagues%2C%20%24friends%20%5D))

```hack
$family = 2 of [ pk(A), pk(B), pk(C) ]; 
$colleagues = 2 of [ pk(D), pk(E), pk(F) ];
$friends = 2 of [ pk(G), pk(H), pk(I) ];

2 of [ $family, $colleagues, $friends ]
```

Or using the alternative `main()` function construct, which allows to express the main policy first and delve into the details later: ([try](https://min.sc/#c=fn%20main%28%29%20%3D%202%20of%20%5B%20%24family%2C%20%24colleagues%2C%20%24friends%20%5D%3B%0A%0A%24family%20%3D%202%20of%20%5B%20pk%28A%29%2C%20pk%28B%29%2C%20pk%28C%29%20%5D%3B%20%0A%24colleagues%20%3D%202%20of%20%5B%20pk%28D%29%2C%20pk%28E%29%2C%20pk%28F%29%20%5D%3B%0A%24friends%20%3D%202%20of%20%5B%20pk%28G%29%2C%20pk%28H%29%2C%20pk%28I%29%20%5D%3B))

```hack
fn main() = 2 of [ $family, $colleagues, $friends ];

$family = 2 of [ pk(A), pk(B), pk(C) ]; 
$colleagues = 2 of [ pk(D), pk(E), pk(F) ];
$friends = 2 of [ pk(G), pk(H), pk(I) ];
```
