### ISSUE TITLE
Might need miniscript library update

### ISSUE THREAD

**Issue by harding** [shesek/minsc#7]
From https://medium.com/blockstream/dont-mix-your-timelocks-d9939b665094

> If a policy contains branches that include mixed timelocks, we refuse to compile them, assuming that the mixed-timelock behavior is not intended.

I assume that means [this minsc script](https://min.sc/#c=after%281%29%20%26%26%20after%28500000001%29%20%26%26%20pk%28A%29) should fail to compile from miniscript policy to miniscript, but it currently works.

Note: I confirmed with @sipa that http://bitcoin.sipa.be/miniscript/ also hasn't been updated for this yet after testing with the same policy minsc generates in the above link.

**Comment by shesek** [comment]
Thanks for reporting this!

This was fixed as of the [migration to rust-miniscript](#1) in [v0.2.0](https://github.com/shesek/minsc/releases/tag/v0.2.0).

The example minsc script you provided now fails with `Cannot lift policies that have a heightlock and timelock combination`.
