### ISSUE TITLE
upgrade readme examples to version 0.2

### ISSUE THREAD

**Issue by philbertw4** [shesek/minsc#8]
I was able to get a local version of minsc running easily enough using Nix by running `nix-shell -p rustc cargo` which dropped me into a shell with rust & cargo installed. I then followed the instructions in the readme to have a local install working. So far so good. 

However, once I started playing with some examples in the readme:
```
echo 'pk(A) && older(1 week)' | minsc -
Error: VarNotFound(Ident("A"))
```

This is probably due to the recent improvements around adding concrete pub keys, etc, so I am just opening this issue so we do not forget to update the readme examples.

**Comment by tkeske** [comment]
`echo '$A = 029ffbe722b147f3035c87cb1c60b9a5947dd49c774cc31e94773478711a929ac0; pk($A) && older(1 week)' | minsc -
`

**Comment by philbertw4** [comment]
Thanks! It seems I had misunderstood the CLI usage considerably.
